apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-service.default.svc.cluster.local:9092"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://localhost:9093"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  KAFKA_NODE_ID: "1"
  KAFKA_NUM_PARTITIONS: "3"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
    - name: "9093"
      port: 9093
      targetPort: 9093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka #should match with template.metadata.labels
  template:
    metadata:
      labels:
        app: kafka  # Should match with selector.matchLabels
    spec:
      containers:
        - image: apache/kafka:latest
          name: kafka
          ports:
            - containerPort: 9092
              protocol: TCP
            - containerPort: 9093
              protocol: TCP
          envFrom:
            - configMapRef:
                name: kafka-config
      restartPolicy: Always
