apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  username: cm9vdA==  # base64-encoded "root"
  password: ZXhhbXBsZQ==  # base64-encoded "example"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  clusterIP: None  # Required for StatefulSet
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sfs
spec:
  serviceName: mongodb-service  # Required for stable pod DNS
  replicas: 1
  selector:
    matchLabels:
      app: mongodb  # Ensure the selector matches the pod labels
  template:
    metadata:
      labels:
        app: mongodb  # Label added here
    spec:
      initContainers:
        - name: init-tcp-fastopen
          image: busybox
          command: ["sh", "-c", "sysctl -w net.ipv4.tcp_fastopen=3"]
          securityContext:
            privileged: true  # Required to modify kernel settings
        - name: init-sysctl
          image: busybox
          command: [ "sh", "-c", "sysctl -w vm.max_map_count=1677720", "sysctl -w vm.swappiness=1" ]
          securityContext:
            privileged: true  # Required to modify sysctl settings
      containers:
        - name: mongodb
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          livenessProbe:
            exec:
              command: ["mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi