apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:latest
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      restartPolicy: Always
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-data
