apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: prometheus
    spec:
      containers:
        - image: prom/prometheus:latest
          name: prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-cm0
              subPath: prometheus.yml
            - mountPath: /prometheus
              name: prometheus-data
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: prometheus.yml
                path: prometheus.yml
            name: prometheus-cm0
          name: prometheus-cm0
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data
