apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'Kafka-Study'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['host.docker.internal:8080']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    service: prometheus
  name: prometheus-cm0
